### ISSUE TITLE
Not showing liquidity for PGL deposited pairs

### ISSUE THREAD

**Issue by tuloski** [pangolindex/interface#12]
In "pool" page it doesn't show my liquidity provided if the PGL tokens were submitted to the PNG contract to farm PNG.
For example I deposited PNG and WAVAX in the WAVAX-PNG pool. I got the PGL equivalent tokens and my liquidity was shown. Then I sent the PGL to the farm and the liquidity disappeared. 
At first it might seems scary because it seems all the liquidity provided was lost.

**Comment by HariSeldon23** [comment]
This is something we're looking into.

Thanks for raising this and sorry it's taken so long to get a response.
