### ISSUE TITLE
Pangolin Bridge?

### ISSUE THREAD

**Issue by gz1968** [pangolindex/interface#23]
Why doesn't Pangolin put a bridge link on it's website to encourage ERC20 holders to crossover, like Zero Exchange?  With nice instructions or videos present to help users through the process.

A friend of mine wanted to buy a small coin on UniSwap with $500. Due to the fees, I advised a different route.  What I was not able to advise him, was to use Pangolin.  I went through the process of buying AVAX.  Sending it to https://wallet-beta.avax.network/ (I use Ledger) to cross from X-chain to C-chain.  Then setting up MetaMask and sending it there.  It was torturous.  No way he could do this.

These Etherium high fees times will be the opportunity for other blockchains to capture users for trading.  So strike while the iron it hot.  Do everything possible to encourage users to crossover.  Because once ETH2.0 hits, that window closes.

I've also mentioned this before on the AVALAB.  Grab the MetaMask code.  Create a AvaWallet with the ability to easily switch chains with the click of a button.  That would open the floodgates into Avalanche for ERC20 people who know MetaMask.

**Comment by gz1968** [comment]
I was told on Discord to use https://aeb.xyz/ .  I actually refused to use it at first, as I thought maybe a hacker trap.  It has a generic domain.  And the link wasn't present on the https://www.avalabs.org/ website.

**Comment by HariSeldon23** [comment]
We're busy looking into this at the moment and have started having discussions around implementation details.

**Comment by HariSeldon23** [comment]
This will be part of the new design
