### ISSUE TITLE
USDC.e not appearing on the new Interface

### ISSUE THREAD

**Issue by HariSeldon23** [pangolindex/interface#252]
When I go to the old site and have the following Lists selected
![image](https://user-images.githubusercontent.com/3041005/146690060-7ad900a3-2629-46e1-a670-8499bd56c206.png)
And then I select the same lists on the new beta site
![image](https://user-images.githubusercontent.com/3041005/146690075-3b475f5c-7e19-496b-be67-43e0afcddd78.png)
I then want to swap to USDC.e however USDC.e does not appear in the new beta site
![image](https://user-images.githubusercontent.com/3041005/146690108-ff09362d-471b-4f17-8eec-96ee271cb714.png)

As part of this we should also ensure that `AVAX DeFi tokens` tokenlist is enabled by default

**Comment by HariSeldon23** [comment]
Weird, it appears now. Not sure if it's a caching issue.

**Comment by SarjuHansaliya** [comment]
Based on your screenshot it looks like you had selected Fuji, so only AVAX is coming in the list.
