### ISSUE TITLE
Unable to chose Connect Wallet in Trust Wallet

### ISSUE THREAD

**Issue by CruiseMan** [pangolindex/interface#3]
Expecting to see Metamask(only avalible atm on web) or actual Trust Wallet logo like other dapps https://github.com/trustwallet/trust-web3-provider#how-to-identify-trust-provider
![IMG_D97DA5C0447F-1](https://user-images.githubusercontent.com/15807643/107595593-f8b2d480-6bc9-11eb-8cd9-c8e7f704061c.jpeg)

**Comment by dasconnor** [comment]
We're working on trust wallet support right now, but currently that is not available
