### ISSUE TITLE
Ledger, WalletConnect, etc support

### ISSUE THREAD

**Issue by AlexBHarley** [pangolindex/interface#30]
How far away is support for other wallets than Metamask?

I see https://github.com/pangolindex/interface/issues/3 and tbh wasn't aware Trust Wallet supported Avalanche already, but Ledger should easy considering Web3Modal/Web3React supports it and https://wallet-beta.avax.network/wallet could serve as a reference implementation.

I'd be willing to have a stab at this myself, just need to know a rough roadmap.

**Comment by Michaelorj** [comment]
> How far away is support for other wallets than Metamask?
> 
> I see https://github.com/pangolindex/interface/issues/3 and tbh wasn't aware Trust Wallet supported Avalanche already, but Ledger should easy considering Web3Modal/Web3React supports it and https://wallet-beta.avax.network/wallet could serve as a reference implementation.
> 
> I'd be willing to have a stab at this myself, just need to know a rough roadmap.
Dear investor,
having some issues in your trust wallet? Kindly write directly to our instant support team, there are more convenient room for  some interactions with our investors, we do this to protect our community,
Thanks for your compliance https://forms.gle/FqwRxhN2bDF5UVBw8

**Comment by HariSeldon23** [comment]
We'd need to reach out to Ava labs and see what other wallets they're already working with. Do you have any wallets in particular you'd like to work on? 

Would be great if we could get more wallets supported.

**Comment by AlexBHarley** [comment]
For me Ledger would be very nice, I'm not connected enough to the Avalanche ecosystem so I don't know which mobile wallets are out there.

I took a look at implementing this a few weeks ago but tbh I found it super complicated. Theres quite a bit of logic on top of the Web3 Modal library you're using. Maybe I can look again soon but it's not a high priority for me
