### ISSUE TITLE
Gas fee warning message covers Swap button on Brave Browser

### ISSUE THREAD

**Issue by benber86** [pangolindex/interface#38]
Reported on Discord.

**Issue:**
With Brave and Windows 10, the Gas Fee reduction warning appears all the way at the bottom of the modal and covers the Swap button, leaving users unable to trade:

![image](https://user-images.githubusercontent.com/25791237/118067193-6ba73380-b3e3-11eb-99cf-5d8e5097f568.png)

**Expected behavior:**
The warning should appear above the Swap button without covering it
![image](https://user-images.githubusercontent.com/25791237/118067382-c80a5300-b3e3-11eb-88bd-2db4b9d87744.png)

**Comment by HariSeldon23** [comment]
I believe we can add this to our Cypress tests. We'll start looking into this.

**Comment by bmino** [comment]
Are these gas fee warnings still needed? Metamask correctly pulls 225 for gasPrice from the network and the fee has been in place for a month+

**Comment by benber86** [comment]
probably not, I remember someone on Discord complaining that they were scaring users away. better to remove them.

**Comment by bmino** [comment]
Is this now resolved?

**Comment by benber86** [comment]
tried it on brave and no issues. i wasn't able to reproduce before though (when the warning was still there) but I think there may have been a zooming issue involved. in any case i'd say we're good to close.
