### ISSUE TITLE
Adding Yield Yak to partners pagae 

### ISSUE THREAD

**Issue by ErichPNG** [pangolindex/interface#464]
Yield Yak asked us to be added to the "Partners" section of Pangolin.exchange
![Yak logo](https://user-images.githubusercontent.com/101758814/165800785-d8e7cff2-b1af-441b-8341-9bf452a6f053.png)

**Comment by HariSeldon23** [comment]
This is actually updated via this repo https://github.com/pangolindex/pangolin.exchange
So closing this for now and we can open it in that repo.

Also important to note that the marketing site will be redesigned to look like this https://www.figma.com/file/usiGsNbAsOB8bEykOM62tR/Pangolin-Business-Main-Page?node-id=0%3A1 so just make sure that it's included in the design by Nirav and Abdullah and then when we start working on it, it'll be included.
